### ISSUE TITLE
连接池资源无法达到maxCap容量上限

### ISSUE THREAD

**Issue by teckick** [nooncall/shazam#1]

**Comment by niubell** [comment]
capacity定义连接池的初始容量、maxCapacity定义连接池的最大容量，实际后端连接数量会根据使用情况在[0,maxCapacity]之间浮动
这里是描述有误，这里能达到的最大连接数量是capacity，连接数在[0,capacity]里浮动，maxCapacity是可以动态设置时最大可设定的数量，是需要通过某个接口去调用的。

解决方案:
我们把描述改掉把，这里的最大值其实是个静态的限定值，而不是一个动态可以达到的值，同事对于连接池的特性及其他功能无影响。
