### ISSUE TITLE
提供插件机制

### ISSUE THREAD

**Issue by teckick** [nooncall/shazam#2]
by [dwdcth](https://github.com/dwdcth)

提供插件机制，比如sql审计和租户管理，用户可以按照规范，自行开发接口，编译成插件（比如so动态库）。

开放生命周期的HooK和获取租户数据，sql路由的接口
比如，BeforeUserConnect, BeforeSqlRoute，BeforeSqlExecute，AfterSqlRoute,AfterSqlExecute，AfterUserDisconnect.在hook里可以获取租户的用户名，和执行的sql。BeforeSqlExecute，AfterSqlExecute可否提供一个context，方便放一些变量

**Comment by teckick** [comment]
关于插件机制大家有哪些建议, 欢迎留言讨论.

**Comment by letian0805** [comment]
go的so插件不大完善，建议用命令行的方式执行插件。
https://github.com/letiantech/hotplugin
上面这个是我两年前写的一个热加载so插件的工具

**Comment by dwdcth** [comment]
不一定需要热加载，监控插件变化，可以提供一个命令，像nginx那样reload即可。
命令行的方式，执行命令会创建进程，这样的开销是否有点大啊

**Comment by teckick** [comment]
这个基本不需要热加载, 主要目的还是方便扩展.

**Comment by letian0805** [comment]
看情况，是要执行常驻进程的任务还是只是偶尔执行。如果偶尔执行，命令行方式就可以了。如果常驻进程，用so可以，但so插件之前有些问题不知道新版本是否解决了。

**Comment by AbelZhou** [comment]
so目前不是很推荐吧

**Comment by abelzhou** [comment]
.so目前不是很推荐吧，reload的话可能改动会有点多，要保证正在运行的处理不受影响。有没有可能用其他脚本语言比如lua，在一些关键位置做hook。
