### ISSUE TITLE
初次使用能不能提供详细的安装部署文档，和最佳实践

### ISSUE THREAD

**Issue by Myshiner** [nooncall/shazam#23]
wiki上的都是快速部署文档，步骤太简要。
有没有更详细的部署文档呢或者最佳实践啥的，供初学者使用。

**Comment by teckick** [comment]
> wiki上的都是快速部署文档，步骤太简要。
> 有没有更详细的部署文档呢或者最佳实践啥的，供初学者使用。

感谢反馈, 我们尽快完善一下文档.

**Comment by bopjiang** [comment]
我在测试shazam时用docker-compose搭建了个环境, 目前配置了分表、读写分离, @Myshiner 可以看看
https://github.com/bopjiang/mysql_sharding_test
