### ISSUE TITLE
每过一段时间就出现use of closed network connection

### ISSUE THREAD

**Issue by dwdcth** [nooncall/shazam#25]
Session write response error, connId: 114992674, err: Conn 114992674: Write(packet) failed: write tcp4   ip1 ->ip2  : use of closed network connection

**Comment by teckick** [comment]
是shazam出错日志吗?

**Comment by dwdcth** [comment]
> 是shazam出错日志吗?

是的

**Comment by teckick** [comment]
> > 是shazam出错日志吗?
> 
> 是的

一般是客户端主动关闭连接导致的

**Comment by dwdcth** [comment]
> > > 是shazam出错日志吗?
> > 
> > 
> > 是的
> 
> 一般是客户端主动关闭连接导致的

好的，我再排查一下
