### ISSUE TITLE
make编译时报错

### ISSUE THREAD

**Issue by Myshiner** [nooncall/shazam#28]
我用git clone 拉取的项目，然后按照快速体验中的make进行编译，编译了一会就直接报错，错误如下：
build github.com/XiaoMi/Gaea/cmd/gaea: cannot load github.com/coreos/etcd/client: unexpected status (https://athens.azurefd.net/github.com/coreos/etcd/@v/v3.3.13+incompatible.zip): 502 Bad Gateway
make: *** [gaea] Error 1

是因为我没有安装etcd吗？

**Comment by eastfisher** [comment]
用master分支构建试试

**Comment by teckick** [comment]
是用的最新的master分支构建的吗?

**Comment by Myshiner** [comment]
对的

**Comment by Myshiner** [comment]
是的
