### ISSUE TITLE
不同namespace用户名密码一样时，会出现使用排在后面的namespace的库

### ISSUE THREAD

**Issue by dwdcth** [nooncall/shazam#3]
如题，我这边配置时有两个库，ip不一样，用户名和密码一样，数据库里的库不一样。于是配置了两个namespace，通过mysql客户端连接时，发现只能看到namespace排在后面的库。建议启动的时候给一下提示用户名冲突，并在文档里说明一下。

**Comment by teckick** [comment]
感谢反馈, 我们优化一下
