### ISSUE TITLE
什么时候可以实现取模分表呢？

### ISSUE THREAD

**Issue by Myshiner** [nooncall/shazam#31]
目前我们线上有按某个字段取模分表的，还有按两个字段分表的，为了兼容目前的数据库，kingshard什么时候支持取模或者复合字段分表呢？有这个计划吗？

**Comment by teckick** [comment]
这是shazam, 不是kingshard.

目前shazam已支持取模分表, 路由规则为`mod`.

**Comment by Myshiner** [comment]
sorry, 提错了
