### ISSUE TITLE
大量”Session read packet error, close it,“，为什么？

### ISSUE THREAD

**Issue by minxinqing** [nooncall/shazam#55]
[2020-06-24 06:47:19] [shazam_proxy] [nicetuan-middle-payment-prod-005] [WARN] [900000001] [github.com/nooncall/shazam/proxy/server.(*Session).Run:session.go:228] Session read packet error, close it, connId: 10433, err: io.ReadFull(header size) failed: read tcp4 127.0.0.1:3306->127.0.0.1:25840: use of closed network connection

出现大量这个警告，是为什么？

**Comment by teckick** [comment]
您好, 感谢反馈!

请先检查一下MySQL的interactive_timeout和wait_timeout的值是否比shazam的namespace slice配置中的idle_timeout的值更大?

```
{
    ...
    "slices": [
        {
            "name": "slice-0",
            "user_name": "root",
            "password": "root",
            "master": "127.0.0.1:3306",
            "capacity": 64,
            "max_capacity": 128,
            "idle_timeout": 3600 // 连接池关闭空闲连接的等待时间
        },
        ...
}
```

**Comment by minxinqing** [comment]
**mysql**
interactive_timeout : 14400
wait_timeout : 86400

**shazam**
session_timeout : 3600
namespace.idle_timeout : 1800
![image](https://user-images.githubusercontent.com/3809601/85489597-cc2e5600-b602-11ea-82d0-bf3d47e9f30e.png)

![image](https://user-images.githubusercontent.com/3809601/85489787-1d3e4a00-b603-11ea-8c55-1abda72d6451.png)

![image](https://user-images.githubusercontent.com/3809601/85489815-2cbd9300-b603-11ea-9a64-f7a522955dc8.png)

**Comment by minxinqing** [comment]
当shazam出现这个日志时，应用侧也会出现 `Warning: PDO::beginTransaction(): MySQL server has gone away`，此时应用会重新创建连接，对业务来说倒是没影响；但是应用侧为什么会报`MySQL server has gone away`呢，之前直接连mysql的时候没发生过，加了shazam后mysql的配置也没变过，难道因为mysql的interactive_timeout（14400）远大于idle_timeout（1800），恰巧应用侧的这个连接闲置时间超过了1800而没超过14400吗？（应用本身有连接池功能）

**Comment by teckick** [comment]
@minxinqing 客户端开autocommit了吗? 如果是没开的话, 客户端会一直持有后端MySQL连接, 且该后端连接不受proxy的idle_timeout约束 (就是说超时也不会主动关闭), 如果mysql侧因为interactive_timeout超时而发起关闭连接, 就会出现上面的warn日志, 这时客户端再发起请求, 因为后端连接被关了, 执行SQL会报错, 导致前端出现 `MySQL server has gone away`.

**Comment by minxinqing** [comment]
这个我现在不确定，稍后我去确定下。如果是这个原因的话，那这个错误就会一直存在，但是从日志来看，这个错误是从上了代理后发生的，并且刚上代理时idle_timeout我设置为70，所以出现频率很高，后来改为1800后，频率降低了很多。

![image](https://user-images.githubusercontent.com/3809601/86235650-55c5c100-bbcb-11ea-8e5b-285175339490.png)

**Comment by jiachinzhao** [comment]
连接中间件的客户端是Go吗， 客户端设置的空闲超时时间是多少

**Comment by minxinqing** [comment]
> 连接中间件的客户端是Go吗， 客户端设置的空闲超时时间是多少

客户端是php，Hyperf框架，基于swoole的常驻进程框架，框架维护连接池，最大闲置时间60秒。

**Comment by teckick** [comment]
@minxinqing 客户端连接池有ping保活吗

**Comment by minxinqing** [comment]
> @minxinqing 客户端连接池有ping保活吗

没有ping保活，在以下两种场景会重新连接：
1、从连接池中取出连接，判断连接闲置时间超过了60秒，重新建立连接并返回。
2、执行SQL语句报 `MySQL server has gone away` 错误时，重新建立连接并重新执行刚刚的语句。

-------------------------------------
这些天我一直想复现生产环境的问题，尝试各种设置，无论是 `namespace.idle_timeout` 大于或者小于应用的`idle_timeout` ，都无法复现；只有在重启shazam后，才会出现和生产环境一样的日志，shazam报`use of closed network connection`，应用报`MySQL server has gone away`，可生产的shazam一直没重启过（shazam进程执行时间超过12天了，应该就是没中断过）。

**Comment by teckick** [comment]
> > @minxinqing 客户端连接池有ping保活吗
> 
> 没有ping保活，在以下两种场景会重新连接：
> 1、从连接池中取出连接，判断连接闲置时间超过了60秒，重新建立连接并返回。
> 2、执行SQL语句报 `MySQL server has gone away` 错误时，重新建立连接并重新执行刚刚的语句。
> 
> 这些天我一直想复现生产环境的问题，尝试各种设置，无论是 `namespace.idle_timeout` 大于或者小于应用的`idle_timeout` ，都无法复现；只有在重启shazam后，才会出现和生产环境一样的日志，shazam报`use of closed network connection`，应用报`MySQL server has gone away`，可生产的shazam一直没重启过（shazam进程执行时间超过12天了，应该就是没中断过）。

客户端连接超时时间是通过gaea.ini配置文件中的session_timeout参数控制的.

**Comment by minxinqing** [comment]
> > > @minxinqing 客户端连接池有ping保活吗
> > 
> > 
> > 没有ping保活，在以下两种场景会重新连接：
> > 1、从连接池中取出连接，判断连接闲置时间超过了60秒，重新建立连接并返回。
> > 2、执行SQL语句报 `MySQL server has gone away` 错误时，重新建立连接并重新执行刚刚的语句。
> > 这些天我一直想复现生产环境的问题，尝试各种设置，无论是 `namespace.idle_timeout` 大于或者小于应用的`idle_timeout` ，都无法复现；只有在重启shazam后，才会出现和生产环境一样的日志，shazam报`use of closed network connection`，应用报`MySQL server has gone away`，可生产的shazam一直没重启过（shazam进程执行时间超过12天了，应该就是没中断过）。
> 
> 客户端连接超时时间是通过gaea.ini配置文件中的session_timeout参数控制的.

尴尬了，我一直以为是 `namespace.idle_timeout` 控制的客户端超时时间，那 `namespace.idle_timeout` 控制的是shazam与mysql之间的最大闲置时间？超过这个值shazam就会放弃连接重连？

我在本地把 `session_timeout` 设置成3秒，应用 `idle_timeout` 设置成60秒后，的确能复现生产的问题了，可生产环境 `session_timeout`我设置的是3600，应用的`idle_timeout`设置的是60，也会有这个情况，我怀疑我的`session_timeout`设置没生效，有接口能看生效的`session_timeout`是多少吗？

**Comment by teckick** [comment]
> 尴尬了，我一直以为是 `namespace.idle_timeout` 控制的客户端超时时间，那 `namespace.idle_timeout` 控制的是shazam与mysql之间的最大闲置时间？超过这个值shazam就会放弃连接重连？

是的, namespace.idle_timeout控制的是gaea连接池关闭多余的空闲连接的超时时间.
 
> 我在本地把 `session_timeout` 设置成3秒，应用 `idle_timeout` 设置成60秒后，的确能复现生产的问题了，可生产环境 `session_timeout`我设置的是3600，应用的`idle_timeout`设置的是60，也会有这个情况，我怀疑我的`session_timeout`设置没生效，有接口能看生效的`session_timeout`是多少吗？

session_timeout只在启动时读取一次, 如果中间修改该值是不会生效的. 要使更新的配置生效需要重启gaea.

不过查看服务配置确实可以考虑提供一个接口出来.

**Comment by minxinqing** [comment]
我记得我应该是改成3600之后重启过proxy，也许我记错了，改天再重启一次看还有没有这个问题。

感谢大佬，这个问题我先关闭了。

**Comment by minxinqing** [comment]
@eastfisher 
我刚试了一下，Proxy主动关闭与客户端的连接，计时是从连接第一次建立时刻D开始，到D+`session_timeout`为止，并不会因为在此期间内客户端多次使用此连接而延长存活时间，是本就这么设计的吗？

**Comment by teckick** [comment]
> @eastfisher
> 我刚试了一下，Proxy主动关闭与客户端的连接，计时是从连接第一次建立时刻D开始，到D+`session_timeout`为止，并不会因为在此期间内客户端多次使用此连接而延长存活时间，是本就这么设计的吗？

不是的, 每次请求后会更新计时器, 最后一次请求后session_timeout内无请求, 才会关闭连接.

**Comment by minxinqing** [comment]
找到问题了，我这边的包太老了，问题2个月前已经修复  https://github.com/nooncall/shazam/pull/53.
