### ISSUE TITLE
你好，请问在proxy位置修改返回的查询结果，我应该看哪部分代码？

### ISSUE THREAD

**Issue by liuzhuan23** [nooncall/shazam#56]
你好，请问在proxy位置修改返回的查询结果，我应该看哪部分代码？可以给个提示吗

**Comment by chicliz** [comment]
![image](https://user-images.githubusercontent.com/43167585/87897243-58566080-ca7d-11ea-81c6-e332699f703a.png)
您好，proxy/plan/plan.go中定义了ExecuteIn接口，selectPlan/deletePlan/insertPlan等都实现了这个接口，具体的sql执行和结果集处理都在这里。

**Comment by liuzhuan23** [comment]
谢谢你的回答
