### ISSUE TITLE
使用一个用户名，多套密码，检测重复用户名，报错仍然有问题

### ISSUE THREAD

**Issue by dwdcth** [nooncall/shazam#6]
我建立了6个namespace,每个的数据库都不同，每个的用户名相同，但是01-03是一套密码，04-06是一套密码，检测报错信息如图：
![image](https://user-images.githubusercontent.com/1883728/64406155-aa83d280-d0b3-11e9-9877-6db1251749ad.png)

期望结果：
database_01,database_02,database_03 用户名密码重复，
database_04，database_05,database_06 用户名密码重复

附件：
[namespace.zip](https://github.com/nooncall/shazam/files/3582471/namespace.zip)

**Comment by teckick** [comment]
重复, 是指当前正在添加的用户名+密码, 与已经存在的用户名+密码重复. 每次加载namespace顺序是随机的, 所以被认为是重复的用户名+密码对应的namespace也不同. 但是, 重复的用户名+密码一定会被检测到并进行警告.
